version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: sqlite3:latest
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    command: ["sqlite3", "/app/db.sqlite3", ".databases"]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - web
    profiles:
      - production
