# Generated by Django 4.2.23 on 2025-08-30 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Blog', max_length=200)),
                ('subdomain', models.SlugField(default='blog', max_length=100)),
                ('auth_token', models.CharField(blank=True, default='', max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_posted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nav', models.TextField(blank=True, default='[Home](/) [Blog](/blog/)')),
                ('content', models.TextField(blank=True, default='Hello World!')),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('meta_image', models.CharField(blank=True, max_length=200)),
                ('lang', models.CharField(blank=True, db_index=True, default='en', max_length=10)),
                ('meta_tag', models.CharField(blank=True, max_length=500)),
                ('blog_path', models.CharField(default='blog', max_length=200)),
                ('header_directive', models.TextField(blank=True)),
                ('footer_directive', models.TextField(blank=True)),
                ('all_tags', models.TextField(default='[]')),
                ('custom_styles', models.TextField(blank=True)),
                ('overwrite_styles', models.BooleanField(choices=[(True, 'Overwrite default styles'), (False, 'Extend default styles')], default=False, verbose_name='')),
                ('favicon', models.CharField(blank=True, default='🐼', max_length=100)),
                ('optimise_images', models.BooleanField(default=True)),
                ('date_format', models.CharField(blank=True, default='d M, Y', max_length=32)),
                ('post_template', models.TextField(blank=True)),
                ('robots_txt', models.TextField(blank=True, default='User-agent: *\nAllow: /')),
                ('rss_alias', models.CharField(blank=True, max_length=100)),
                ('codemirror_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=200)),
                ('alias', models.CharField(blank=True, db_index=True, max_length=200)),
                ('published_date', models.DateTimeField(blank=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('all_tags', models.TextField(default='[]')),
                ('publish', models.BooleanField(db_index=True, default=True)),
                ('is_page', models.BooleanField(db_index=True, default=False)),
                ('content', models.TextField()),
                ('canonical_url', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('meta_image', models.CharField(blank=True, max_length=200)),
                ('lang', models.CharField(blank=True, db_index=True, max_length=10)),
                ('class_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stylesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('identifier', models.SlugField(max_length=100, unique=True)),
                ('css', models.TextField(blank=True)),
                ('external', models.BooleanField(default=False)),
                ('image', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
